spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delhi_metro
    username: delhimetro
    password: 1234
    hikari:
      maximum-pool-size: 20
      idle-timeout: 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect