spring:
  datasource:
    url: jdbc:mysql://delhi-metro-backend-db-1.chbdhnauut12.ap-northeast-1.rds.amazonaws.com:3306/delhi_metro_db
    username: admin
    password: profilebaba_123
    hikari:
      maximum-pool-size: 20
      idle-timeout: 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect